title: 简历 - Java开发 - 杨磊 - 15198065639

aboutme:
  name: 杨磊
  sex: 男
  age: 22
  email: 774373492@qq.com
  phone: 15198065639
  github: https://github.com/yanglei802
  city: 上海
  job: Java开发
  edu: 成都工业学院 | 软件工程 | 本科

update: 2020年06月7日